branch-defaults:
  master:
    environment: clinical
environment-defaults:
  clinical:
    branch: null
    repository: null
global:
  application_name: beiwe-application
  branch: null
  default_ec2_keyname: jake-conscious-insights
  default_platform: Python 2.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
